# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deadLine',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
