# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registerTime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
