# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20170630_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
