# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20170630_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=32),
        ),
    ]
