# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20170701_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='personalInfo',
            new_name='PersonalInfo',
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
