# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20170701_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinfo',
            name='bloodType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1990, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='constellation',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='profile',
            field=models.CharField(default='', max_length=80),
        ),
    ]
